import java.util.Scanner;
public class Special{
public static void main(String args[]) {
Scanner m= new Scanner(System.in);
System.out.println("enter anything");
String  x= m.next(); 
Int  age= m.nextInt(); 

   if(x==female)
      { else if(age>1 &&age<58)
System.out.println(“the percentage of interest is 8.2%”);
      }
      else if(age>59 && age<100)
      {
System.out.println("the percentage of interest is 9.2%.");
      }
Else if(x==male)
{
      { else if(age>1 &&age<58)
System.out.println(“the percentage of interest is 8.4%”);
      }
      else 
      {
System.out.println("the percentage of interest is 10.4%.");
      }
    }
}
}
